apiVersion: apps/v1
kind: Deployment
metadata:
  name: bob
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bob
  template:
    metadata:
      labels:
        app: bob
    spec:
      containers:
        - name: ecrimage
          image: rahulwagh17/jhooq-docker-demo:jhooq-docker-demo
          command:
          - cat
          tty: true
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: bob
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: bob